[package]
name = "pickeat-server"
version = "0.2.0"
authors = ["Valentin.Roussel <valentin.rssl@gmail.com>"]
edition = "2024"

[profile.release]
lto = "thin"

[dependencies]
anyhow = "1.0.98"
askama = { version = "0.16.0", features = ["code-in-doc"] }
axum = { version = "0.8.4", features = ["http2", "macros", "multipart"] }
clap = { version = "4.5.41", features = ["derive"] }
openssl = { version = "0.10.73", features = ["vendored"] }
reqwest = "0.12.22"
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["migrate", "postgres", "runtime-tokio", "uuid"] }
thiserror = "2.0.12"
tokio = { version = "1.47.0", features = ["rt-multi-thread"] }
toml = "0.9.5"
tower = "0.5.3"
tower-http = { version = "0.6.10", features = ["trace", "request-id", "util"] }
tower-livereload = "0.10.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
uuid = { version = "1.23.1", features = [ "v7", "serde"] }

[dev-dependencies]
dotenv = "0.15.0"
serde_qs = "1.1.1"
tempfile = "3.20.0"

[profile.dev.package.askama_derive]
opt-level = 3
