[package]
name = "pickeat"
version = "0.1.0"
authors = ["Valentin.Roussel <valentin.rssl@gmail.com>"]
edition = "2018"
#todo try 2021

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
chrono = { version = "0.4.23", features = ["serde"] }
clap = { version = "4.0.26", features = ["derive"] }
config = "0.13.2"
log = "0.4.17"
serde = "1.0.147"
serde_json = "1.0.88"
simplelog = "0.12.0"
sqlx = { version = "0.6", features = [ "runtime-actix-rustls", "postgres", "time" ] }
time = { version = "0.3.17", features = ["serde"] }

[profile.release]
lto = "thin"

[profile.dev.package.sqlx-macros]
opt-level = 3
