- block:
  - name: Generate DB model diff
    become: false
    command:
      cmd: >
        pgmodeler-cli
          --input ../backend/db/pick_eat.dbm
          --diff --drop-missing
          --host "{{ ansible_host }}"
          --user pickeat_model
          --passwd "{{ pickeat_model_pwd }}"
          --compare-to pickeat
          --save
          --output /tmp/diff.sql
    delegate_to: localhost
    changed_when: false
    check_mode: false
    register: pgmodelercli_output

  - name: Check if there is a diff to apply
    become: false
    set_fact:
      diff_to_apply: '{{ "Saving diff to file" in pgmodelercli_output.stdout }}'

  - name: Generate distant temp file
    tempfile:
      prefix: pickeat_sql_diff_
      suffix: .sql
    register: tmpfile
    when: diff_to_apply

  - name: Send diff file to host
    copy:
      src: '/tmp/diff.sql'
      dest: "{{ tmpfile.path | default('/tmp/pickeat_sql_diff.sql') }}"
      mode: '0444'
    when: diff_to_apply

  - name: Apply diff
    community.postgresql.postgresql_script:
      login_unix_socket: "{{ pg_unix_socket }}"
      login_user: pickeat
      login_db: pickeat
      path: "{{ tmpfile.path }}"
    when: diff_to_apply and not ansible_check_mode

  always:
    - name: Remove distant temp file
      file:
        path: "{{ tmpfile.path }}"
        state: absent
      when: tmpfile is defined and tmpfile.path is defined
