- name: Define db dsn
  meta: noop
  vars:
    dsn: &db_dsn
      login_unix_socket: "{{ pg_unix_socket }}"
      login_user: "postgres"
      login_db: "pickeat"

- name: Revoke default privs public
  postgresql_privs:
    <<: *db_dsn
    roles: PUBLIC
    type: schema
    objs: public
    state: absent
    privs: CREATE,USAGE

- name: Grant schema priv to pickeat user
  postgresql_privs:
    <<: *db_dsn
    roles: pickeat
    type: schema
    objs: public
    state: present
    privs: CREATE,USAGE

- name: Grant usage schema priv to pickeat_model and pickeat_app users
  postgresql_privs:
    <<: *db_dsn
    roles: pickeat_model,pickeat_app
    type: schema
    objs: public
    state: present
    privs: USAGE

- name: Grant tables priv to pickeat_app user
  postgresql_privs:
    <<: *db_dsn
    roles: pickeat_app
    type: table
    objs: ALL_IN_SCHEMA
    state: present
    privs: SELECT,INSERT,UPDATE,DELETE

# If pickeat user creates a new table, pickeat_app should
# be able to access it
- name: Grant default tables priv to pickeat_app user
  postgresql_privs:
    <<: *db_dsn
    roles: pickeat_app
    target_roles: pickeat
    type: default_privs
    objs: TABLES
    state: present
    privs: SELECT,INSERT,UPDATE,DELETE
