- name: Define db dsn
  meta: noop
  vars:
    dsn: &db_dsn
      login_unix_socket: "{{ pg_unix_socket }}"
      login_user: "postgres"
      login_db: "postgres"

- name: create DB role (pickeat)
  postgresql_user:
    <<: *db_dsn
    name: pickeat
    role_attr_flags: CREATEROLE,LOGIN

- name: create DB role (pickeat_model)
  postgresql_user:
    <<: *db_dsn
    name: pickeat_model
    password: "{{ pickeat_model_pwd }}"

- name: create DB role (pickeat_app)
  postgresql_user:
    <<: *db_dsn
    name: pickeat_app
