- name: Setup pg_hba (pickeat)
  postgresql_pg_hba:
    dest: "{{ pg_hba_path }}"
    contype: local
    databases: pickeat
    method: peer
    users: pickeat

- name: Setup pg_hba (pickeat_model)
  postgresql_pg_hba:
    dest: "{{ pg_hba_path }}"
    contype: host
    address: all
    databases: pickeat
    method: scram-sha-256
    users: pickeat_model

- name: Setup pg_hba (pickeat_app)
  postgresql_pg_hba:
    dest: "{{ pg_hba_path }}"
    contype: local
    databases: pickeat
    method: peer
    users: pickeat_app
    options: 'map=pickeat_app'

- name: Setup pg_ident
  lineinfile:
    line: pickeat_app pickeat pickeat_app
    dest: "{{ pg_ident_path }}"
