- name: Allow postgres group to run commands as postgres user
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%postgres'
    line: '%postgres ALL=(postgres) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add current user to postgres group
  user:
    name: "{{ ansible_user }}"
    groups: postgres
    append: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create pickeat group
  group:
    name: pickeat
    state: present

- name: Create pickeat user
  user:
    name: pickeat
    group: pickeat

- name: Allow pickeat group to run commands as pickeat user
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%pickeat'
    line: '%pickeat ALL=(pickeat) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add current user to pickeat group
  user:
    name: "{{ ansible_user }}"
    groups: pickeat
    append: true
  ignore_errors: "{{ ansible_check_mode }}"
