- name: Restart postgres
  become_user: root
  systemd:
    name: postgresql
    state: restarted

- name: Reload postgres conf
  become_user: postgres
  postgresql_query:
    login_unix_socket: "{{ pg_unix_socket }}"
    db: postgres
    query: "SELECT pg_reload_conf()"
    as_single_query: true
