- become: true
  become_user: postgres
  block:
  - name: Ensute backups dir exists
    ansible.builtin.file:
      path: $HOME/backups
      state: directory
      mode: '0700'

  - name: Daily db backup (odd days)
    ansible.builtin.cron:
      name: Daily db backup (odd days)
      minute: "0"
      hour: "4"
      day: "1-31/2"
      job: "pg_dumpall --clean --if-exists > $HOME/backups/pg_dumpall_daily_1.sql"

  - name: Daily db backup (even days)
    ansible.builtin.cron:
      name: Daily db backup (even days)
      minute: "0"
      hour: "4"
      day: "2-31/2"
      job: "pg_dumpall --clean --if-exists > $HOME/backups/pg_dumpall_daily_2.sql"

  - name: Weekly db backup
    ansible.builtin.cron:
      name: Weekly db backup
      minute: "0"
      hour: "3"
      weekday: "0"
      job: "pg_dumpall --clean --if-exists > $HOME/backups/pg_dumpall_weekly.sql"

  - name: Monthly db backup
    ansible.builtin.cron:
      name: Monthly db backup
      minute: "0"
      hour: "2"
      day: "1"
      job: "pg_dumpall --clean --if-exists > $HOME/backups/pg_dumpall_monthly.sql"
