- name: Install nginx
  apt:
    update_cache: true
    cache_valid_time: 86400
    name:
      - nginx

- name: Copy static files
  copy:
    src: to_deploy/frontend/
    dest: "/var/www/{{ pickeat_site_url }}/"
    mode: '0444'

- name: Create site in nginx conf
  template:
    src: pickeat_nginx_site.j2
    dest: "/etc/nginx/sites-available/{{ pickeat_site_url }}"
    mode: '0444'

- name: Enable site
  file:
    path: "/etc/nginx/sites-enabled/{{ pickeat_site_url }}"
    state: link
    src: "../sites-available/{{ pickeat_site_url }}"


- name: Reload nginx service
  systemd:
    enabled: true
    state: reloaded
    name: nginx.service
