- name: Install nginx
  apt:
    update_cache: true
    cache_valid_time: 86400
    name:
      - nginx
      - libnginx-mod-http-brotli-static

- name: Make sure nginx service is enabled and running
  systemd:
    enabled: true
    state: started
    name: nginx.service

- name: Copy static files
  tags: app
  synchronize:
    src: to_deploy/frontend/
    dest: "/var/www/{{ pickeat_site_url }}/"
    delete: true
    rsync_opts:
    - "--chmod=F444"
  notify: Reload nginx service

- name: Copy robots.txt
  tags: app
  template:
    src: robots.txt.j2
    dest: "/var/www/{{ pickeat_site_url }}/robots.txt"
    mode: '0644'
  notify: Reload nginx service

- name: Setup sitemap_gen
  tags: app
  block:
    - name: Copy sitemap_gen conf
      template:
        src: sitemap_gen.conf.j2
        dest: /etc/pickeat/sitemap_gen.conf
        mode: '0644'
        owner: pickeat
        group: pickeat

    - name: Copy sitemap_gen script
      copy:
        src: sitemap_gen.py
        dest: /usr/local/bin/sitemap_gen.py
        mode: '0744'
        owner: pickeat
        group: pickeat

    - name: Setup sitemap_gen cron
      cron:
        name: sitemap_gen.py daily run
        job: "/usr/local/bin/sitemap_gen.py -c /etc/pickeat/sitemap_gen.conf -l /var/log/pickeat/sitemap_gen.log"
        hour: "0"
        user: pickeat

- name: Update default nginx conf
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    mode: '0644'
  notify: Reload nginx service

- name: Create site in nginx conf
  template:
    src: pickeat_nginx_site.j2
    dest: "/etc/nginx/sites-available/{{ pickeat_site_url }}"
    mode: '0444'
  notify: Reload nginx service

- name: Disable default site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Reload nginx service

- name: Enable pick-eat site
  file:
    path: "/etc/nginx/sites-enabled/{{ pickeat_site_url }}"
    state: link
    src: "../sites-available/{{ pickeat_site_url }}"
  notify: Reload nginx service
