- name: Install redis-server
  apt:
    update_cache: true
    cache_valid_time: 86400
    name:
      - redis-server

- name: Install redis conf
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis-pickeat.conf
    mode: '0440'
    owner: redis
    group: redis
  notify: Restart redis

- name: Make sure redis service is enabled and running
  systemd:
    enabled: true
    state: started
    name: redis-server@pickeat.service

- name: Add current user to redis group
  user:
    name: "{{ ansible_user }}"
    groups: redis
    append: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install pickeat binary
  tags: app
  copy:
    src: "to_deploy/backend/{{ ansible_architecture }}/pickeat"
    dest: /usr/local/bin/pickeat
    mode: '0544'
    owner: pickeat
    group: pickeat
  notify: Restart pickeat systemd service

- name: Create pickeat conf directory
  file:
    path: /etc/pickeat/
    state: directory
    recurse: true
    owner: pickeat
    group: pickeat

- name: Create pickeat var directory
  file:
    path: /var/log/pickeat/
    state: directory
    recurse: true
    owner: pickeat
    group: pickeat

- name: Install pickeat conf
  template:
    src: pickeat.conf.j2
    dest: /etc/pickeat/pickeat.conf
    mode: '0440'
    owner: pickeat
    group: pickeat
  notify: Restart pickeat systemd service

- name: lingering
  block:
    - name: Check if pickeat user is lingering
      stat:
        path: "/var/lib/systemd/linger/pickeat"
      register: user_lingering

    - name: Enable lingering if needed
      command: "loginctl enable-linger pickeat"
      when:
        - not user_lingering.stat.exists

- name: systemd
  block:
    - name: Create pickeat systemd directory
      become_user: pickeat
      file:
        path: "$HOME/.config/systemd/user/"
        state: directory
        recurse: true

    - name: Install pickeat systemd service
      become_user: pickeat
      copy:
        src: pickeat.service
        dest: "$HOME/.config/systemd/user/pickeat.service"
        mode: '0440'

    - name: set XDG_RUNTIME_DIR env var in .bashrc
      become_user: pickeat
      lineinfile:
        line: "export XDG_RUNTIME_DIR=\"/run/user/$UID\""
        dest: "$HOME/.bashrc"
  notify: Restart pickeat systemd service

- name: Make sure pickeat server is enabled and running
  become_user: pickeat
  systemd:
    daemon_reload: true
    enabled: true
    scope: user
    state: started
    name: pickeat.service
