server {
    location / {
        proxy_pass http://127.0.0.1:4242;
    }

    location /_tower-livereload/event-stream {
        return 301 http://127.0.0.1:4242/_tower-livereload/event-stream;
    }

    location /assets/ {
        root /srv/www;
    }

    location /images/ {
        root /srv/www;
    }
}
