#!/usr/bin/env ansible-playbook

- name: Install dependencies
  hosts: backend
  become: true
  tasks:
    - apt:
        update_cache: true
        cache_valid_time: 86400
        name: acl

- name: Setup postgres DB
  hosts: backend
  become: true
  roles:
    - postgres
    - pickeat_db

- name: Install pickeat server
  hosts: backend
  become: true
  roles:
    - pickeat_server
