#!/usr/bin/env ansible-playbook

- name: Update apt cache if it's never been done
  hosts: backend
  become: true
  tasks:
    - stat:
        path: /var/lib/apt/periodic/update-success-stamp
      register: stat_result
    - apt:
        update_cache: true
      when: not stat_result.stat.exists

- name: Install dependencies
  hosts: backend
  become: true
  tasks:
    - apt:
        update_cache: true
        cache_valid_time: 86400
        name: acl

- name: Setup postgres DB
  tags: database
  hosts: backend
  become: true
  roles:
    - postgres
    - pickeat_db

- name: Install pickeat server
  hosts: backend
  become: true
  roles:
    - pickeat_server
