#!/usr/bin/env ansible-playbook

- name: Install dependencies
  hosts: backend
  become: true
  tasks:
    - apt:
        update_cache: true
        cache_valid_time: 86400
        name: acl

- name: Setup postgres DB
  hosts: backend
  become: true
  tags: db
  roles:
    - postgres
    - pickeat_db
