#!/usr/bin/env ansible-playbook

- name: Update apt cache if it's never been done
  hosts: frontend
  become: true
  tasks:
    - stat:
        path: /var/lib/apt/periodic/update-success-stamp
      register: stat_result
    - apt:
        update_cache: true
      when: not stat_result.stat.exists

- name: Create ssl certificate
  hosts: frontend
  become: true
  roles:
    - certbot
  vars:
    domains:
      - "{{ pickeat_site_url }}"
      - "*.{{ pickeat_site_url }}"
    cert_name: "{{ pickeat_site_url }}"
    app_key: "{{ ovh_app.app_key }}"
    app_secret: "{{ ovh_app.app_secret }}"
    consumer_key: "{{ ovh_app.consumer_key }}"
    emergency_email: "{{ certbot_emergency_email }}"

- name: Install pickeat front
  hosts: frontend
  become: true
  roles:
    - pickeat_front
