- name: Install certbot
  apt:
    update_cache: true
    cache_valid_time: 86400
    name:
      - python3-certbot
      - python3-certbot-dns-ovh

- name: Create .secrets directory
  file:
    path: "$HOME/.secrets/certbot/"
    state: directory
    recurse: true
    owner: root
    group: root

- name: Copy ovh credentials
  template:
    src: ovh.conf.j2
    dest: "$HOME/.secrets/certbot/ovh.conf"
    mode: '0400'
    owner: root
    group: root

- name: Generate certificate
  shell:
    cmd: certbot certonly --dns-ovh --dns-ovh-credentials "$HOME/.secrets/certbot/ovh.conf" -d "{{ domains | join(',') }}" --cert-name "{{ cert_name }}" -m "{{ emergency_email }}" --agree-tos
    creates: "/etc/letsencrypt/live/{{ cert_name }}"

- name: Make sure certbot.timer (auto renewal cron) is active
  systemd:
    daemon_reload: true
    enabled: true
    scope: system
    state: started
    name: certbot.timer
