name: Rust CI

on:
  push:
    branches: [ "v2" ]
  pull_request:
    branches: [ "v2" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  DB_SUPERUSER_PASSWORD: postgres
  DB_PICKEAT_PASSWORD: pickeat
  DB_PICKEAT_APP_PASSWORD: app

jobs:
  check-sqlx:
    runs-on: ubuntu-latest

    steps:
    - name: Set DATABASE_URL
      run: |
        echo "DATABASE_URL=postgres://pickeat:${DB_PICKEAT_PASSWORD}@localhost:5432/pickeat" >> $GITHUB_ENV
    - uses: Swatinem/rust-cache@v2
    - uses: actions/checkout@v4
    - name: Launch db container
      run: docker compose up --build -d
    - name: Install sqlx-cli
      run: cargo install sqlx-cli --no-default-features --features postgres
    - name: Run SQL migrations
      run: sqlx migrate run --source db/migrations/
    - name: Check sqlx prepare
      run: cargo sqlx prepare --check


  build:
    needs: check-sqlx
    runs-on: ubuntu-latest

    steps:
    - uses: Swatinem/rust-cache@v2
    - uses: actions/checkout@v4
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run rustfmt
      run: cargo fmt -- --check
    - name: Build docker image (builder stage, for testing purpose)
      run: docker build --platform linux/amd64,linux/arm64 --target builder -t builder .
    - name: Launch db container
      run: docker compose up --build -d
    - name: Run tests
      run: docker run -e DB_PICKEAT_APP_PASSWORD -e DB_PICKEAT_PASSWORD --network=host builder cargo test --release
    - name: Build docker image (runtime stage)
      run: docker build --platform linux/amd64,linux/arm64 -t pickeat-server:${{ github.sha }} .
    - name: Tag image for staging
      run: docker tag pickeat-server:${{ github.sha }} pickeat-server:staging
