name: Rust CI

on:
  push:
    branches: [ "v2" ]
  pull_request:
    branches: [ "v2" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  DB_SUPERUSER_PASSWORD: postgres

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]

    steps:
    - name: Rustup update
      run: rustup update
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run rustfmt
      run: cargo fmt -- --check
