name: Rust CI

on:
  push:
    branches: [ "v2" ]
  pull_request:
    branches: [ "v2" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  DB_SUPERUSER_PASSWORD: postgres
  DB_PICKEAT_PASSWORD: pickeat
  DB_PICKEAT_APP_PASSWORD: app

jobs:
  check-sqlx:
    runs-on: ubuntu-latest

    steps:
    - name: Set DATABASE_URL
      run: |
        echo "DATABASE_URL=postgres://pickeat:${DB_PICKEAT_PASSWORD}@localhost:5432/pickeat" >> $GITHUB_ENV
    - uses: Swatinem/rust-cache@v2
    - uses: actions/checkout@v4
    - name: Launch db container
      run: docker compose up --build -d
    - name: Install sqlx-cli
      run: cargo install sqlx-cli --no-default-features --features postgres
    - name: Run SQL migrations
      run: sqlx migrate run --source db/migrations/
    - name: Check sqlx prepare
      run: cargo sqlx prepare --check


  build:
    needs: check-sqlx
    runs-on: ubuntu-latest

    steps:
    - uses: Swatinem/rust-cache@v2
    - uses: actions/checkout@v4
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run rustfmt
      run: cargo fmt -- --check
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build docker image (builder stage, for testing purpose)
      uses: docker/build-push-action@v6
      with:
        target: builder
        load: true
        tags: builder
        cache-from: type=registry,ref=vroussel/pick-eat:buildcache
        platforms: linux/amd64
    - name: Launch db container
      run: docker compose up --build -d
    - name: Run tests
      run: docker run --rm -e DB_PICKEAT_APP_PASSWORD -e DB_PICKEAT_PASSWORD --network=host builder cargo test --release
    - name: Build docker image (runtime stage)
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: vroussel/pick-eat:staging
        cache-from: type=registry,ref=vroussel/pick-eat:buildcache
        cache-to: type=registry,ref=vroussel/pick-eat:buildcache,mode=max
